name: "godot-ci test"
on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main

env:
  GODOT_VERSION: 4.4.1
  EXPORT_NAME: bretagne
  EXPORT_DIR: export
  PROJECT_PATH: .

jobs:
  test:
    runs-on: ubuntu-22.04  # Use 22.04 with godot 4
    container:
      image: barichello/godot-ci:4.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: false
          fetch-depth: 0
      
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Pull LFS
        env:
          LFS_PAT: ${{ secrets.LFS_PAT }}
        working-directory: ${{ github.workspace }}
        timeout-minutes: 2
        run: |
          echo $(pwd)
          # https://github.com/actions/checkout/issues/415#issuecomment-2143700018
          git lfs install --skip-repo
          # Configure Git to use the LFS_PAT for authentication
          git config --local http.https://lfs.bent.party/.extraheader "Authorization: Bearer $LFS_PAT"
          # Pull LFS objects
          git lfs pull

      - run: godot --headless --import
      
      - name: Test
        timeout-minutes: 2
        run: |
          godot --headless -d -s --path "$PWD" addons/gut/gut_cmdln.gd -gjunit_xml_file "$GITHUB_WORKSPACE/junit.xml" -gdir=res://test/ -gprefix=test_ | while read -r line; do
            echo "$line"
            if [ "$(echo "$line" | grep 'Results saved to')" ]; then
              PID=$(ps -ef | grep '[g]odot' | awk '{print $2}')
              if [ -n "$PID" ]; then
                (sleep 2 && kill "$PID" && echo "Killed process with PID $PID") &
              else
                echo "No matching process found to kill"
              fi
              exit 0
            fi
          done

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
